application: training-log
version: 1
runtime: go
api_version: go1

handlers:
- url: /apidocs/(.*?)/(.*\.(js|html|css))
  static_files: static/swagger/\1/\2
  upload: static/swagger/(.*?)/(.*\.(js|html|css))

- url: /.*
  script: _go_app